EPSILON = "&"
BLANK = " "
SPECIAL = "!@#$%_-+=,.:;/"
DIGIT = "0123456789"
LOWER_CASE = "abcdefghijklmnopqrstuvxwyz"
UPPER_CASE = "ABCDEFGHIJKLMNOPQRSTUVXWYZ"
ALPHANUMERIC = DIGIT + LOWER_CASE + UPPER_CASE + BLANK
SYMBOL = DIGIT + LOWER_CASE + UPPER_CASE + BLANK + SPECIAL
